### ISSUE TITLE
Automated choice of smoothing parameter TODO:

### ISSUE THREAD

**Issue by eldad-a** [eldad-a/natural-cubic-smoothing-splines#1]
- [ ] Functions for auto-smoothing parameter choice need to be reviewed (make sure they follow the definitions in the original publications). 
- [ ] Consider keeping only the LOG variants, dropping the non-log ones (when is it preferable to use the non-log version?) -> keep LOG for backwards compatibility; output warning if non-None
- [ ] Consider removing the multi-dimensional version (what is the Reference for the current multi-dimensional implementation?). Can output warning when non-single dimension data is provided, or revert to vectorized implementation.
